name: habesha_dating
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.7.0
  flutter_launcher_icons: ^0.13.1
  go_router: ^14.2.0
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  hooks_riverpod: ^2.5.1
  url_strategy: ^0.2.0
  shared_preferences: ^2.2.3
  http: ^1.2.1
  palette_generator: ^0.3.3+3
  cached_network_image: ^3.3.1
  camera: ^0.11.0+1
  image_picker: ^1.1.2
  image_picker_web: ^4.0.0
  mime_type: ^1.0.0
  path: ^1.9.0
  file_picker: ^8.0.6
  flutter_svg: ^2.0.10+1
  keyboard_dismisser: ^3.0.0
  get: ^4.6.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  go_router_builder: ^2.7.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/logo.jpg
    - assets/images/logo.png
    - assets/images/google.png
    - assets/images/Call.svg
    - assets/images/message.svg
    - assets/images/settings.svg
    - assets/images/user.svg

    - assets/data.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    - family: Caros
      fonts:
        - asset: assets/fonts/cretype Caros Black Italic.otf
          weight: 900
          style: italic
        - asset: assets/fonts/cretype Caros Black.otf
          weight: 900
        - asset: assets/fonts/cretype Caros Bold Italic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/cretype Caros Bold.otf
          weight: 700
        - asset: assets/fonts/cretype Caros ExtraBold Italic.otf
          weight: 800
          style: italic
        - asset: assets/fonts/cretype Caros ExtraBold.otf
          weight: 800
        - asset: assets/fonts/cretype Caros ExtraLight Italic.otf
          weight: 200
          style: italic
        - asset: assets/fonts/cretype Caros ExtraLight.otf
          weight: 200
        - asset: assets/fonts/cretype Caros Heavy Italic.otf
          weight: 200
          style: italic
        - asset: assets/fonts/cretype Caros Heavy.otf
          weight: 900
        - asset: assets/fonts/cretype Caros Light Italic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/cretype Caros Light.otf
          weight: 300
        - asset: assets/fonts/cretype Caros Medium Italic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/cretype Caros Medium.otf
          weight: 500
        - asset: assets/fonts/cretype Caros Thin Italic.otf
          weight: 100
          style: italic
        - asset: assets/fonts/cretype Caros Thin.otf
          weight: 100
        - asset: assets/fonts/cretype Caros Italic.otf
          style: italic
        # - asset: fonts/cretype Caros.otf
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  # fonts:
  #   - family: Caros
  #     fonts:
  #       - assets/fonts/cretype Caros Black Italic.otf
  #       - assets/fonts/cretype Caros Black.otf
  #       - assets/fonts/cretype Caros Bold Italic.otf
  #       - assets/fonts/cretype Caros Bold.otf
  #       - assets/fonts/cretype Caros ExtraBold Italic.otf
  #       - assets/fonts/cretype Caros ExtraBold.otf
  #       - assets/fonts/cretype Caros ExtraLight Italic.otf
  #       - assets/fonts/cretype Caros ExtraLight.otf
  #       - assets/fonts/cretype Caros Heavy Italic.otf
  #       - assets/fonts/cretype Caros Heavy.otf
  #       - assets/fonts/cretype Caros Light Italic.otf
  #       - assets/fonts/cretype Caros Light.otf
  #       - assets/fonts/cretype Caros Medium Italic.otf
  #       - assets/fonts/cretype Caros Medium.otf
  #       - assets/fonts/cretype Caros Thin Italic.otf
  #       - assets/fonts/cretype Caros Thin.otf
  #       - assets/fonts/cretype Caros Italic.otf
  #       - assets/fonts/cretype Caros.otf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
